#!/bin/bash
#
# AccuWeather status block for i3blocks
#
# USAGE:
#   weather.sh <locationcode>
#
# Copyright (C) 2007 Michael Seiler
# Copyright (C) 2016 Oleksandr Dunayevskyy  <oleksandr.dunayevskyy@gmail.com>
#


LOCATION=${1:-EUR|UA|UP015|ODESSA}

# Should be 0 or 1; 0 for F, 1 for C
METRIC=1

curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=$METRIC\&locCode\=$LOCATION | perl -ne '
use utf8;
binmode(STDOUT, ":utf8");
if (/Currently:/)
{
   chomp;
   /\<title\>Currently: (.*)?\<\/title\>/;
   my @values=split(":",$1);
   $values[1] =~ s/C/°C/;
   my $icon="?";


   $icon_sun = "";
   $icon_cloud = "";
   $icon_rain = "";
   $icon_wind = "";
   $icon_snow = "";
   $icon_night = "";
   if(   $values[0] eq "Sunny"
      || $values[0] eq "Mostly Sunny"
      || $values[0] eq "Partly Sunny"
      || $values[0] eq "Intermittent Clouds"
      || $values[0] eq "Hazy Sunshine"
      || $values[0] eq "Hazy Sunshine"
      || $values[0] eq "Hot")
   {
      $icon = $icon_sun;
   }
   if(   $values[0] eq "Mostly Cloudy"
      || $values[0] eq "Cloudy"
      || $values[0] eq "Dreary (Overcast)"
      || $values[0] eq "Fog")
   {
      $icon = $icon_cloud;
   }
   if(   $values[0] eq "Showers"
      || $values[0] eq "Mostly Cloudy w/ Showers"
      || $values[0] eq "Partly Sunny w/ Showers"
      || $values[0] eq "T-Storms"
      || $values[0] eq "Mostly Cloudy w/ T-Storms"
      || $values[0] eq "Partly Sunny w/ T-Storms"
      || $values[0] eq "Rain")
   {
      $icon = $icon_rain;
   }
   if( $values[0] eq "Windy")
   {
      $icon = $icon_wind;
   }
   if(   $values[0] eq "Flurries"
      || $values[0] eq "Mostly Cloudy w/ Flurries"
      || $values[0] eq "Partly Sunny w/ Flurries"
      || $values[0] eq "Snow"
      || $values[0] eq "Mostly Cloudy w/ Snow"
      || $values[0] eq "Ice"
      || $values[0] eq "Sleet"
      || $values[0] eq "Freezing Rain"
      || $values[0] eq "Rain and Snow"
      || $values[0] eq "Cold")
   {
      $icon = $icon_snow;
   }
   if(   $values[0] eq "Clear"
      || $values[0] eq "Mostly Clear"
      || $values[0] eq "Partly Cloudy"
      || $values[0] eq "Intermittent Clouds"
      || $values[0] eq "Hazy Moonlight"
      || $values[0] eq "Mostly Cloudy"
      || $values[0] eq "Partly Cloudy w/ Showers"
      || $values[0] eq "Mostly Cloudy w/ Showers"
      || $values[0] eq "Partly Cloudy w/ T-Storms"

      || $values[0] eq "Mostly Cloudy w/ Flurries"
      || $values[0] eq "Mostly Cloudy w/ Snow")
   {
      $icon = $icon_night;
   }
   # long text
   print "$icon $values[1], $values[0]\n";
   # short text
   print "$icon $values[1]\n";
}'
