#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.

killall xbindkeys
killall compton
killall mpd
killall lxqt-notificationd
killall conky
killall tint2
killall qjackctl
killall -9 jackd
killall volumeicon
killall cbatticon
killall gxkb
killall transmission-qt
killall owncloud

#wallpaper-wallhaven-dl.sh -m favorites -n  2 -m favorites &
#export XDG_CURRENT_DESKTOP=LXDE
dbus-update-activation-environment --systemd DISPLAY

xrandr --dpi 96
setxkbmap -layout "us,ru" -option "compose:ralt" -option "grp:alt_shift_toggle"
xset dpms 600
xrdb -m ~/.Xresources
xhost +
xbindkeys

# Make Caps Lock act as Mod4
#xmodmap -e "remove lock = Caps_Lock"
#xmodmap -e "add mod4 = Caps_Lock"

compton &

# start xiccd and kill it after 4 seconds
#timeout 4s xiccd &

mpd .config/mpd/mpd.conf
lxqt-notificationd &
nitrogen --restore
sleep 0.3
conky -c ~/.config/conky/sidebar.lua -x 4 -y 4 &
tint2 &
qjackctl &
#nm-applet &
#blueberry-tray &
volumeicon &
cbatticon &
gxkb &
transmission-qt &
#chromium &
owncloud &
#thunar --daemon &
#virt-manager &
#uzbl-tabbed &
#gvim &
#steam &

