#!/bin/sh

#wallpaper-wallhaven-dl.sh -m favorites -n  2 -m favorites &
export XDG_CURRENT_DESKTOP=LXDE
dbus-update-activation-environment --systemd DISPLAY
xrandr --dpi 96
setxkbmap -layout "us,ru" -option "compose:ralt" -option "grp:alt_shift_toggle"
xset dpms 600
xrdb -m ~/.Xresources
xhost +
compton &
# start xiccd and kill it after 4 seconds
#timeout 4s xiccd &
lxqt-notificationd &
nitrogen --restore
sleep 0.3
conky -c ~/.config/conky/sidebar.lua -x 4 -y 4 &
tint2 &
qjackctl &
#nm-applet &
#blueberry-tray &
volumeicon &
cbatticon &
gxkb &
transmission-qt &
#chromium &
owncloud &
#thunar --daemon &
#virt-manager &
#uzbl-tabbed &
#gvim &
#steam &

